syntax = "proto3";

package trigger.v1;

import "google/protobuf/any.proto";
import "buf/validate/validate.proto";

option go_package = "github.com/ionut-maxim/motoras/api/trigger/v1;triggerv1";

message Trigger {
  string id = 1 [(buf.validate.field).string.uuid = true];
  string name = 2 [(buf.validate.field).string = {
    min_len: 1,
    max_len: 255
  }];
  string type = 3 [(buf.validate.field).string.min_len = 1];
  string workflow_id = 4 [(buf.validate.field).string.uuid = true];
  google.protobuf.Any data = 5 [(buf.validate.field).required = true];
}

message CreateRequest {
  Trigger trigger = 1;
}

message CreateResponse {
  string id = 1 [(buf.validate.field).string.uuid = true];
}

message UpdateRequest {
  Trigger trigger = 1;
}

message UpdateResponse {
  string id = 1 [(buf.validate.field).string.uuid = true];
}

message GetRequest {
  string id = 1 [(buf.validate.field).string.uuid = true];
}

message GetResponse {
  Trigger trigger = 1;
}

message DeleteRequest {
  string id = 1 [(buf.validate.field).string.uuid = true];
}

message DeleteResponse {
  string id = 1 [(buf.validate.field).string.uuid = true];
}

message ListRequest {
}

message ListResponse {
  repeated Trigger triggers = 1;
}

service TriggerService {
  rpc Create(CreateRequest) returns (CreateResponse) {}
  rpc Get(GetRequest) returns (GetResponse) {}
  rpc Update(UpdateRequest) returns (UpdateResponse) {}
  rpc Delete(DeleteRequest) returns (DeleteResponse) {}
  rpc List(ListRequest) returns (ListResponse) {}
}
