// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: workflow/v1/workflow.proto

package workflowv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/ionut-maxim/motoras/api/workflow/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// WorkflowServiceName is the fully-qualified name of the WorkflowService service.
	WorkflowServiceName = "workflow.v1.WorkflowService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// WorkflowServiceCreateProcedure is the fully-qualified name of the WorkflowService's Create RPC.
	WorkflowServiceCreateProcedure = "/workflow.v1.WorkflowService/Create"
	// WorkflowServiceGetProcedure is the fully-qualified name of the WorkflowService's Get RPC.
	WorkflowServiceGetProcedure = "/workflow.v1.WorkflowService/Get"
	// WorkflowServiceUpdateProcedure is the fully-qualified name of the WorkflowService's Update RPC.
	WorkflowServiceUpdateProcedure = "/workflow.v1.WorkflowService/Update"
	// WorkflowServiceDeleteProcedure is the fully-qualified name of the WorkflowService's Delete RPC.
	WorkflowServiceDeleteProcedure = "/workflow.v1.WorkflowService/Delete"
	// WorkflowServiceListProcedure is the fully-qualified name of the WorkflowService's List RPC.
	WorkflowServiceListProcedure = "/workflow.v1.WorkflowService/List"
	// WorkflowServiceStartProcedure is the fully-qualified name of the WorkflowService's Start RPC.
	WorkflowServiceStartProcedure = "/workflow.v1.WorkflowService/Start"
)

// WorkflowServiceClient is a client for the workflow.v1.WorkflowService service.
type WorkflowServiceClient interface {
	Create(context.Context, *connect.Request[v1.CreateRequest]) (*connect.Response[v1.CreateResponse], error)
	Get(context.Context, *connect.Request[v1.GetRequest]) (*connect.Response[v1.GetResponse], error)
	Update(context.Context, *connect.Request[v1.UpdateRequest]) (*connect.Response[v1.UpdateResponse], error)
	Delete(context.Context, *connect.Request[v1.DeleteRequest]) (*connect.Response[v1.DeleteResponse], error)
	List(context.Context, *connect.Request[v1.ListRequest]) (*connect.Response[v1.ListResponse], error)
	Start(context.Context, *connect.Request[v1.StartRequest]) (*connect.Response[v1.StartResponse], error)
}

// NewWorkflowServiceClient constructs a client for the workflow.v1.WorkflowService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewWorkflowServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) WorkflowServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	workflowServiceMethods := v1.File_workflow_v1_workflow_proto.Services().ByName("WorkflowService").Methods()
	return &workflowServiceClient{
		create: connect.NewClient[v1.CreateRequest, v1.CreateResponse](
			httpClient,
			baseURL+WorkflowServiceCreateProcedure,
			connect.WithSchema(workflowServiceMethods.ByName("Create")),
			connect.WithClientOptions(opts...),
		),
		get: connect.NewClient[v1.GetRequest, v1.GetResponse](
			httpClient,
			baseURL+WorkflowServiceGetProcedure,
			connect.WithSchema(workflowServiceMethods.ByName("Get")),
			connect.WithClientOptions(opts...),
		),
		update: connect.NewClient[v1.UpdateRequest, v1.UpdateResponse](
			httpClient,
			baseURL+WorkflowServiceUpdateProcedure,
			connect.WithSchema(workflowServiceMethods.ByName("Update")),
			connect.WithClientOptions(opts...),
		),
		delete: connect.NewClient[v1.DeleteRequest, v1.DeleteResponse](
			httpClient,
			baseURL+WorkflowServiceDeleteProcedure,
			connect.WithSchema(workflowServiceMethods.ByName("Delete")),
			connect.WithClientOptions(opts...),
		),
		list: connect.NewClient[v1.ListRequest, v1.ListResponse](
			httpClient,
			baseURL+WorkflowServiceListProcedure,
			connect.WithSchema(workflowServiceMethods.ByName("List")),
			connect.WithClientOptions(opts...),
		),
		start: connect.NewClient[v1.StartRequest, v1.StartResponse](
			httpClient,
			baseURL+WorkflowServiceStartProcedure,
			connect.WithSchema(workflowServiceMethods.ByName("Start")),
			connect.WithClientOptions(opts...),
		),
	}
}

// workflowServiceClient implements WorkflowServiceClient.
type workflowServiceClient struct {
	create *connect.Client[v1.CreateRequest, v1.CreateResponse]
	get    *connect.Client[v1.GetRequest, v1.GetResponse]
	update *connect.Client[v1.UpdateRequest, v1.UpdateResponse]
	delete *connect.Client[v1.DeleteRequest, v1.DeleteResponse]
	list   *connect.Client[v1.ListRequest, v1.ListResponse]
	start  *connect.Client[v1.StartRequest, v1.StartResponse]
}

// Create calls workflow.v1.WorkflowService.Create.
func (c *workflowServiceClient) Create(ctx context.Context, req *connect.Request[v1.CreateRequest]) (*connect.Response[v1.CreateResponse], error) {
	return c.create.CallUnary(ctx, req)
}

// Get calls workflow.v1.WorkflowService.Get.
func (c *workflowServiceClient) Get(ctx context.Context, req *connect.Request[v1.GetRequest]) (*connect.Response[v1.GetResponse], error) {
	return c.get.CallUnary(ctx, req)
}

// Update calls workflow.v1.WorkflowService.Update.
func (c *workflowServiceClient) Update(ctx context.Context, req *connect.Request[v1.UpdateRequest]) (*connect.Response[v1.UpdateResponse], error) {
	return c.update.CallUnary(ctx, req)
}

// Delete calls workflow.v1.WorkflowService.Delete.
func (c *workflowServiceClient) Delete(ctx context.Context, req *connect.Request[v1.DeleteRequest]) (*connect.Response[v1.DeleteResponse], error) {
	return c.delete.CallUnary(ctx, req)
}

// List calls workflow.v1.WorkflowService.List.
func (c *workflowServiceClient) List(ctx context.Context, req *connect.Request[v1.ListRequest]) (*connect.Response[v1.ListResponse], error) {
	return c.list.CallUnary(ctx, req)
}

// Start calls workflow.v1.WorkflowService.Start.
func (c *workflowServiceClient) Start(ctx context.Context, req *connect.Request[v1.StartRequest]) (*connect.Response[v1.StartResponse], error) {
	return c.start.CallUnary(ctx, req)
}

// WorkflowServiceHandler is an implementation of the workflow.v1.WorkflowService service.
type WorkflowServiceHandler interface {
	Create(context.Context, *connect.Request[v1.CreateRequest]) (*connect.Response[v1.CreateResponse], error)
	Get(context.Context, *connect.Request[v1.GetRequest]) (*connect.Response[v1.GetResponse], error)
	Update(context.Context, *connect.Request[v1.UpdateRequest]) (*connect.Response[v1.UpdateResponse], error)
	Delete(context.Context, *connect.Request[v1.DeleteRequest]) (*connect.Response[v1.DeleteResponse], error)
	List(context.Context, *connect.Request[v1.ListRequest]) (*connect.Response[v1.ListResponse], error)
	Start(context.Context, *connect.Request[v1.StartRequest]) (*connect.Response[v1.StartResponse], error)
}

// NewWorkflowServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewWorkflowServiceHandler(svc WorkflowServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	workflowServiceMethods := v1.File_workflow_v1_workflow_proto.Services().ByName("WorkflowService").Methods()
	workflowServiceCreateHandler := connect.NewUnaryHandler(
		WorkflowServiceCreateProcedure,
		svc.Create,
		connect.WithSchema(workflowServiceMethods.ByName("Create")),
		connect.WithHandlerOptions(opts...),
	)
	workflowServiceGetHandler := connect.NewUnaryHandler(
		WorkflowServiceGetProcedure,
		svc.Get,
		connect.WithSchema(workflowServiceMethods.ByName("Get")),
		connect.WithHandlerOptions(opts...),
	)
	workflowServiceUpdateHandler := connect.NewUnaryHandler(
		WorkflowServiceUpdateProcedure,
		svc.Update,
		connect.WithSchema(workflowServiceMethods.ByName("Update")),
		connect.WithHandlerOptions(opts...),
	)
	workflowServiceDeleteHandler := connect.NewUnaryHandler(
		WorkflowServiceDeleteProcedure,
		svc.Delete,
		connect.WithSchema(workflowServiceMethods.ByName("Delete")),
		connect.WithHandlerOptions(opts...),
	)
	workflowServiceListHandler := connect.NewUnaryHandler(
		WorkflowServiceListProcedure,
		svc.List,
		connect.WithSchema(workflowServiceMethods.ByName("List")),
		connect.WithHandlerOptions(opts...),
	)
	workflowServiceStartHandler := connect.NewUnaryHandler(
		WorkflowServiceStartProcedure,
		svc.Start,
		connect.WithSchema(workflowServiceMethods.ByName("Start")),
		connect.WithHandlerOptions(opts...),
	)
	return "/workflow.v1.WorkflowService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case WorkflowServiceCreateProcedure:
			workflowServiceCreateHandler.ServeHTTP(w, r)
		case WorkflowServiceGetProcedure:
			workflowServiceGetHandler.ServeHTTP(w, r)
		case WorkflowServiceUpdateProcedure:
			workflowServiceUpdateHandler.ServeHTTP(w, r)
		case WorkflowServiceDeleteProcedure:
			workflowServiceDeleteHandler.ServeHTTP(w, r)
		case WorkflowServiceListProcedure:
			workflowServiceListHandler.ServeHTTP(w, r)
		case WorkflowServiceStartProcedure:
			workflowServiceStartHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedWorkflowServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedWorkflowServiceHandler struct{}

func (UnimplementedWorkflowServiceHandler) Create(context.Context, *connect.Request[v1.CreateRequest]) (*connect.Response[v1.CreateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("workflow.v1.WorkflowService.Create is not implemented"))
}

func (UnimplementedWorkflowServiceHandler) Get(context.Context, *connect.Request[v1.GetRequest]) (*connect.Response[v1.GetResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("workflow.v1.WorkflowService.Get is not implemented"))
}

func (UnimplementedWorkflowServiceHandler) Update(context.Context, *connect.Request[v1.UpdateRequest]) (*connect.Response[v1.UpdateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("workflow.v1.WorkflowService.Update is not implemented"))
}

func (UnimplementedWorkflowServiceHandler) Delete(context.Context, *connect.Request[v1.DeleteRequest]) (*connect.Response[v1.DeleteResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("workflow.v1.WorkflowService.Delete is not implemented"))
}

func (UnimplementedWorkflowServiceHandler) List(context.Context, *connect.Request[v1.ListRequest]) (*connect.Response[v1.ListResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("workflow.v1.WorkflowService.List is not implemented"))
}

func (UnimplementedWorkflowServiceHandler) Start(context.Context, *connect.Request[v1.StartRequest]) (*connect.Response[v1.StartResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("workflow.v1.WorkflowService.Start is not implemented"))
}
