// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: trigger/v1/trigger.proto

package triggerv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/ionut-maxim/motoras/api/trigger/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// TriggerServiceName is the fully-qualified name of the TriggerService service.
	TriggerServiceName = "trigger.v1.TriggerService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// TriggerServiceCreateProcedure is the fully-qualified name of the TriggerService's Create RPC.
	TriggerServiceCreateProcedure = "/trigger.v1.TriggerService/Create"
	// TriggerServiceUpdateProcedure is the fully-qualified name of the TriggerService's Update RPC.
	TriggerServiceUpdateProcedure = "/trigger.v1.TriggerService/Update"
	// TriggerServiceListProcedure is the fully-qualified name of the TriggerService's List RPC.
	TriggerServiceListProcedure = "/trigger.v1.TriggerService/List"
)

// TriggerServiceClient is a client for the trigger.v1.TriggerService service.
type TriggerServiceClient interface {
	Create(context.Context, *connect.Request[v1.CreateRequest]) (*connect.Response[v1.CreateResponse], error)
	Update(context.Context, *connect.Request[v1.UpdateRequest]) (*connect.Response[v1.UpdateResponse], error)
	List(context.Context, *connect.Request[v1.ListRequest]) (*connect.Response[v1.ListResponse], error)
}

// NewTriggerServiceClient constructs a client for the trigger.v1.TriggerService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewTriggerServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) TriggerServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	triggerServiceMethods := v1.File_trigger_v1_trigger_proto.Services().ByName("TriggerService").Methods()
	return &triggerServiceClient{
		create: connect.NewClient[v1.CreateRequest, v1.CreateResponse](
			httpClient,
			baseURL+TriggerServiceCreateProcedure,
			connect.WithSchema(triggerServiceMethods.ByName("Create")),
			connect.WithClientOptions(opts...),
		),
		update: connect.NewClient[v1.UpdateRequest, v1.UpdateResponse](
			httpClient,
			baseURL+TriggerServiceUpdateProcedure,
			connect.WithSchema(triggerServiceMethods.ByName("Update")),
			connect.WithClientOptions(opts...),
		),
		list: connect.NewClient[v1.ListRequest, v1.ListResponse](
			httpClient,
			baseURL+TriggerServiceListProcedure,
			connect.WithSchema(triggerServiceMethods.ByName("List")),
			connect.WithClientOptions(opts...),
		),
	}
}

// triggerServiceClient implements TriggerServiceClient.
type triggerServiceClient struct {
	create *connect.Client[v1.CreateRequest, v1.CreateResponse]
	update *connect.Client[v1.UpdateRequest, v1.UpdateResponse]
	list   *connect.Client[v1.ListRequest, v1.ListResponse]
}

// Create calls trigger.v1.TriggerService.Create.
func (c *triggerServiceClient) Create(ctx context.Context, req *connect.Request[v1.CreateRequest]) (*connect.Response[v1.CreateResponse], error) {
	return c.create.CallUnary(ctx, req)
}

// Update calls trigger.v1.TriggerService.Update.
func (c *triggerServiceClient) Update(ctx context.Context, req *connect.Request[v1.UpdateRequest]) (*connect.Response[v1.UpdateResponse], error) {
	return c.update.CallUnary(ctx, req)
}

// List calls trigger.v1.TriggerService.List.
func (c *triggerServiceClient) List(ctx context.Context, req *connect.Request[v1.ListRequest]) (*connect.Response[v1.ListResponse], error) {
	return c.list.CallUnary(ctx, req)
}

// TriggerServiceHandler is an implementation of the trigger.v1.TriggerService service.
type TriggerServiceHandler interface {
	Create(context.Context, *connect.Request[v1.CreateRequest]) (*connect.Response[v1.CreateResponse], error)
	Update(context.Context, *connect.Request[v1.UpdateRequest]) (*connect.Response[v1.UpdateResponse], error)
	List(context.Context, *connect.Request[v1.ListRequest]) (*connect.Response[v1.ListResponse], error)
}

// NewTriggerServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewTriggerServiceHandler(svc TriggerServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	triggerServiceMethods := v1.File_trigger_v1_trigger_proto.Services().ByName("TriggerService").Methods()
	triggerServiceCreateHandler := connect.NewUnaryHandler(
		TriggerServiceCreateProcedure,
		svc.Create,
		connect.WithSchema(triggerServiceMethods.ByName("Create")),
		connect.WithHandlerOptions(opts...),
	)
	triggerServiceUpdateHandler := connect.NewUnaryHandler(
		TriggerServiceUpdateProcedure,
		svc.Update,
		connect.WithSchema(triggerServiceMethods.ByName("Update")),
		connect.WithHandlerOptions(opts...),
	)
	triggerServiceListHandler := connect.NewUnaryHandler(
		TriggerServiceListProcedure,
		svc.List,
		connect.WithSchema(triggerServiceMethods.ByName("List")),
		connect.WithHandlerOptions(opts...),
	)
	return "/trigger.v1.TriggerService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case TriggerServiceCreateProcedure:
			triggerServiceCreateHandler.ServeHTTP(w, r)
		case TriggerServiceUpdateProcedure:
			triggerServiceUpdateHandler.ServeHTTP(w, r)
		case TriggerServiceListProcedure:
			triggerServiceListHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedTriggerServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedTriggerServiceHandler struct{}

func (UnimplementedTriggerServiceHandler) Create(context.Context, *connect.Request[v1.CreateRequest]) (*connect.Response[v1.CreateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("trigger.v1.TriggerService.Create is not implemented"))
}

func (UnimplementedTriggerServiceHandler) Update(context.Context, *connect.Request[v1.UpdateRequest]) (*connect.Response[v1.UpdateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("trigger.v1.TriggerService.Update is not implemented"))
}

func (UnimplementedTriggerServiceHandler) List(context.Context, *connect.Request[v1.ListRequest]) (*connect.Response[v1.ListResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("trigger.v1.TriggerService.List is not implemented"))
}
