// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: workflow/v1/workflow.proto

package workflowv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Manifest      string                 `protobuf:"bytes,1,opt,name=manifest,proto3" json:"manifest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRequest) Reset() {
	*x = CreateRequest{}
	mi := &file_workflow_v1_workflow_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequest) ProtoMessage() {}

func (x *CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_v1_workflow_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequest.ProtoReflect.Descriptor instead.
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return file_workflow_v1_workflow_proto_rawDescGZIP(), []int{0}
}

func (x *CreateRequest) GetManifest() string {
	if x != nil {
		return x.Manifest
	}
	return ""
}

type CreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateResponse) Reset() {
	*x = CreateResponse{}
	mi := &file_workflow_v1_workflow_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResponse) ProtoMessage() {}

func (x *CreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_v1_workflow_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResponse.ProtoReflect.Descriptor instead.
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return file_workflow_v1_workflow_proto_rawDescGZIP(), []int{1}
}

func (x *CreateResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_workflow_v1_workflow_proto protoreflect.FileDescriptor

const file_workflow_v1_workflow_proto_rawDesc = "" +
	"\n" +
	"\x1aworkflow/v1/workflow.proto\x12\vworkflow.v1\"+\n" +
	"\rCreateRequest\x12\x1a\n" +
	"\bmanifest\x18\x01 \x01(\tR\bmanifest\" \n" +
	"\x0eCreateResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id2V\n" +
	"\x0fWorkflowService\x12C\n" +
	"\x06Create\x12\x1a.workflow.v1.CreateRequest\x1a\x1b.workflow.v1.CreateResponse\"\x00B;Z9github.com/ionut-maxim/motoras/api/workflow/v1;workflowv1b\x06proto3"

var (
	file_workflow_v1_workflow_proto_rawDescOnce sync.Once
	file_workflow_v1_workflow_proto_rawDescData []byte
)

func file_workflow_v1_workflow_proto_rawDescGZIP() []byte {
	file_workflow_v1_workflow_proto_rawDescOnce.Do(func() {
		file_workflow_v1_workflow_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_workflow_v1_workflow_proto_rawDesc), len(file_workflow_v1_workflow_proto_rawDesc)))
	})
	return file_workflow_v1_workflow_proto_rawDescData
}

var file_workflow_v1_workflow_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_workflow_v1_workflow_proto_goTypes = []any{
	(*CreateRequest)(nil),  // 0: workflow.v1.CreateRequest
	(*CreateResponse)(nil), // 1: workflow.v1.CreateResponse
}
var file_workflow_v1_workflow_proto_depIdxs = []int32{
	0, // 0: workflow.v1.WorkflowService.Create:input_type -> workflow.v1.CreateRequest
	1, // 1: workflow.v1.WorkflowService.Create:output_type -> workflow.v1.CreateResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_workflow_v1_workflow_proto_init() }
func file_workflow_v1_workflow_proto_init() {
	if File_workflow_v1_workflow_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_workflow_v1_workflow_proto_rawDesc), len(file_workflow_v1_workflow_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_workflow_v1_workflow_proto_goTypes,
		DependencyIndexes: file_workflow_v1_workflow_proto_depIdxs,
		MessageInfos:      file_workflow_v1_workflow_proto_msgTypes,
	}.Build()
	File_workflow_v1_workflow_proto = out.File
	file_workflow_v1_workflow_proto_goTypes = nil
	file_workflow_v1_workflow_proto_depIdxs = nil
}
